-- Cau 36:
SELECT MASP,SUM(SL) [TONG SO LUONG]
FROM  HOADON A, CTHD B
WHERE A.SOHD=B.SOHD AND MONTH(NGHD)=10 AND YEAR(NGHD)=2006 
GROUP BY MASP 


-- Cau 37:
SELECT MONTH(NGHD) THANG,SUM(TRIGIA) [DOANH THU]
FROM  HOADON A, CTHD B
WHERE A.SOHD=B.SOHD AND YEAR(NGHD)=2006 
GROUP BY MONTH(NGHD)


-- Cau 38:
SELECT *
FROM  HOADON
WHERE SOHD IN (SELECT SOHD
    FROM  CTHD
    GROUP BY SOHD
    HAVING COUNT(DISTINCT MASP)>=4)


-- Cau 39:
SELECT *
FROM  HOADON
WHERE SOHD IN (SELECT SOHD
    FROM  CTHD A, SANPHAM B
    WHERE A.MASP=B.MASP AND NUOCSX='VIET NAM'
    GROUP BY SOHD
    HAVING COUNT(DISTINCT A.MASP)=3)


-- Cau 40:
SELECT *
FROM  KHACHHANG
WHERE MAKH IN (SELECT MAKH
    FROM  HOADON
    GROUP BY MAKH
    HAVING COUNT(SOHD)>=ALL(SELECT  COUNT(SOHD)
          FROM  HOADON
          GROUP BY MAKH))


-- Cau 41:
SELECT MONTH(NGHD) THANG
FROM  HOADON
WHERE YEAR(NGHD)=2006
GROUP BY MONTH(NGHD)
HAVING SUM(TRIGIA)>=ALL(SELECT SUM(TRIGIA)
     FROM  HOADON
     WHERE YEAR(NGHD)=2006
     GROUP BY MONTH(NGHD))


-- Cau 42:
SELECT B.MASP, TENSP
FROM  SANPHAM A,CTHD B, HOADON C
WHERE A.MASP=B.MASP AND B.SOHD=C.SOHD AND YEAR(NGHD)=2006
GROUP BY B.MASP,TENSP
HAVING SUM(SL)>=ALL(SELECT  SUM(SL)
     FROM  CTHD A, HOADON B
     WHERE A.SOHD=B.SOHD AND YEAR(NGHD)=2006
     GROUP BY MASP)


-- Cau 43:
SELECT NUOCSX,MASP, TENSP
FROM  SANPHAM A
WHERE GIA=(SELECT MAX(GIA)
   FROM  SANPHAM B
   WHERE A.NUOCSX=B.NUOCSX)
GROUP BY NUOCSX,MASP,TENSP


-- Cau 44:
SELECT NUOCSX
FROM  SANPHAM
GROUP BY NUOCSX
HAVING COUNT(DISTINCT GIA)>=3


-- Cau 45:
SELECT *
FROM  KHACHHANG
WHERE MAKH IN (SELECT A.MAKH
    FROM  HOADON A, KHACHHANG B
    WHERE A.MAKH=B.MAKH AND
      DOANHSO IN (SELECT TOP 10 DOANHSO
        FROM  KHACHHANG
        ORDER BY DOANHSO DESC) 
    GROUP BY A.MAKH
    HAVING COUNT(SOHD)>=ALL(SELECT  COUNT(SOHD)
          FROM  HOADON A, KHACHHANG B
          WHERE A.MAKH=B.MAKH AND
            DOANHSO IN (SELECT TOP 10 DOANHSO
               FROM  KHACHHANG
               ORDER BY DOANHSO DESC)  
          GROUP BY A.MAKH))
